config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end
  resources :users, only: [:new, :create]
  resources(:sessions, {only: [:new, :create, :destroy]})
                       #key   #symbol
  # resources :sessions, only: [:new, :create, :destroy]
  # Above line is same as the following:
  # resources(:sessions, {:only => [:new, :create, :destroy]})
  
  # symbol itself can be the value to another key in a hash
  # the whole thing only: ... :destroy is a hash,
  # only is the key, the valus is the followed-up array 

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews
  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  validates :comment, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews
  has_many :products, through: :reviews
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # private methods can only be invoked inside current Controller
  # public methods can be invoked within other Controllers
  private

  def current_user
    # Q: What's the purpose of ||= ?
    # A: ||是 或运算符,如果前面的变量为空,那么就会执行后面的表达式,进行赋值,
    #    只赋值一次,以后运行这段代码的时候,会直接返回@current_user的当前值
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # Q: Session is something that should be at top of a web service
    # A: 这里的session不是自定义的,而是从ActionController::Base
    #    里继承的
  end

  # Purpose of defining helper_method is: To use the method
  # in other Controllers and View (application.html.erb)
  # helper_method is available to both Controllers and Views
  helper_method :current_user

  #Q: Is this a helper method?
  #A: No, this method is going to be available to all Controllers
  #   but not available to Views
  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end


# Q: Why define current_user in ApplicationController?
# A: method defined in ApplicationController can be invoked
#    by other user-defined Controllers
#    But if a helper method is defined in a user-defined
#    Controller, that method can't be accessed by other
#    user-defined Controllers？

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    search = params[:search]
    if search
      @products = Product.where("LOWER(name) LIKE ?", "%#{search.downcase}%")
                # Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
      # SELECT * FROM products WHERE LOWER(name) LIKE '%streamed%'

      # case insensitive search, ILIKE is not supported on SQLite
      # @products = Produce.where("name ILIKE ?", "&#{search}%")
    else
      @products = Product.all
    end

    @products = @products.order('products.created_at DESC').page(params[:page])

    respond_to do |format|
      format.html do
      # if this request is an AJAX request (XMLHttpRequest)
        if request.xhr?
           render @products  # render _product partial for each product
           # render partial: "product", collection: @products    # equivalent to above line
        else
          render :index
        end
      end

      format.js do |format|

      end

      format.json { render json: @products.as_json }

    end
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_url
      # render :create # render create.js.erb  # window.location.replace("http://stackoverflow.com");
      # respond_to do |format|
      #   format.js
      # end
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_filter :load_product
  before_action :ensure_logged_in, only: [:create, :destroy]
  before_action :load_product

  def show
    # @review = Review.find(params[:id])
  end

  def create
    # Q: What is the difference between .build & .new?
    # A: build should be applied to a collection, while new should be applied to a class
    # Review.new(product_id: @product.id)  # This line is funtionally equivalent as next line
    @review = @product.reviews.build(review_params)
    @review.user = current_user
    respond_to do |format|
      if @review.save
        # redirect_to products_path, notice: 'Review created successfully'
        # Q: Using redirect_to when an ajax call happens is pointless, since XHR blocks
        # redirection anyways. One won't see current page being redirected.
        # So what's the point of writing the line below?
        format.html { redirect_to product_path(@product.id), notice:'Review added!' }
        format.js {}
      else
        # render 'products/show' # render a View, not render an action
        # Q: Why render show path without passing in an id parameter?
        format.html { render 'products/show', alert: 'There was an error!' }
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email]) # Note the difference between find() & find_by()
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id # This is how to set a hash's key with a value
      redirect_to products_url, notice: "Logged in!" # Q: Where can I see this notice message? Who this message is written for?
    else
      flash.now[:alert] = "Invalid email or password" # Q: It works the same with or withour '.now'
      # alert: "Invalid email or password" # Can't write like this, causes error
      render "new"
    end
  end

  def destroy
    # Up to now, this app only allow ONE user to log in at one time
    session[:user_id] = nil
    # session.reset!
    redirect_to products_url, notice: "Logged out!"
  end

end

# find returns an error if it fails to find the thing
# find_by returns nil if it fails to find the thing

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private
  def  user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Q: How to comment multiple lines in a View? -->
<!-- <% flash.each do |name, msg| -%> -->
      <!-- <%= content_tag :div, msg, class: name %> -->
      <!-- Q: How to look up content_tag in Rails API? -->
    <!-- <% end -%> -->

    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>
    
    <%= yield %>

    <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/products/_product.html.erb
<ul>
  <li><p><%= product.name %></p></li>
  <li><p><%= product.description %></p></li>
  <li><p><%= number_to_currency(product.formatted_price) %></p></li>
</ul>
<p>See reviews about <%= link_to "#{product.name}", product_path(product) %>
</p><br>

app/views/products/_review_form_errors.html.erb
<% if @review.errors.present? %>
  <div id="error_explanation">
  <% @review.errors.full_messages.each do |error| %>
    <div class="alert">
      <%= error %>
    </div>
  <% end %>
<% end %>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <div class="review">
    <p class="comment">
      <%= review.comment %>
    </p>
    <!-- Q: Why must it check if review.user != nil? If remove this line, line 17 fails to work. -->
    <% if review.user != nil %>
      <div class="poster">
        Posted by <em><%= review.user.name %></em>
        Added on: <%= review.created_at %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/products/create.js.erb
$('body').append("<%= escape_javascript(render @product) %>");

app/views/products/edit.html.erb
<h1>Edit product: <%= @product.name %></h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing Products</h1>
<%= link_to 'New Product', new_product_path %>
<!-- renders a helpful message with numbers of displayed vs. total entries -->
<h1><small><%= page_entries_info @products %></small></h1>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<div id="products">
  <%= render @products %>
</div>

<!-- outputs several pagination links such as « First ‹ Prev ... 2 3 4 5 6 7 8 9 10 ... Next › Last » -->
<%= paginate @products %>

app/views/products/index.js.erb
// $('#products').html("<p>The \"quote\"</p>");
// $('#products').html("<%= j(render(partial: 'product', collection: @products)) %>");
// j() is alias for escape_javascript(), which actually means escape html punctuations for javascript.

<% if params[:search] && params[:page].nil? %>
  $('#products').html("<%= j(render @products) %>");
<% else %>
  $('#products').append('<%= j render(@products) %>');
<% end %>

$('.pagination').replaceWith('<%= j paginate(@products) %>');

app/views/products/index.json.erb
im json

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
 
<p>Name: <%= @product.name %></p>
<p>Description: <%= @product.description %></p>
<p>Price: <%= number_to_currency(@product.formatted_price) %></p>

<h3>Reviews for <%= @product.name %></h3>
<div id="review-list">
  <%= render :partial => "reviews" %>
</div>

<% if current_user %>
  <h4>New Review</h4>

  <%= form_for([@product, @review], remote: true) do |f| %>
    <div id="review-form-errors">
      <%= render :partial => "products/review_form_errors" %>
    </div>

    <div class="field">
      <%= f.label :comment %><br>
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>

<script type="text/javascript">
  $(function() {
    // Where is this #new_review from?
     $("#new_review")
        .on('ajax:beforeSend', function() { // set this code to happen just before the ajax request is made
          $("input[type='submit']") // make changes to the submit button
            .val('Saving...') // change the text on the button
            .attr('disabled', 'disabled'); // disable the button
        })
        .on('ajax:complete', function() {
          $("input[type='submit']")
            .val('Create Review')
            .removeAttr('disabled');
        });
  });
</script>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
  $("#new_review")[0].reset();
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
  
<% end %>